version: '3.9'

services:
  mysql-uaa-db:
    image: mysql:8.0
    container_name: ctn_mysql-uaa-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uaa-service-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      
  phpmyadmin-uaa-service:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ctn_phpmyadmin-uaa-db
    restart: unless-stopped
    ports:
      - 8085:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-uaa-db
      PMA_USER: user 
      PMA_PASSWORD: user
    depends_on:
      - mysql-uaa-db
      
      
volumes:
  mysql_data:
    driver: local
    