server:
  port: 8081
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uaa-service-db?createDatabseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
    password: user
    username: user
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: uaa-service
#  cloud:
#    discovery:
#      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#security:
#  basic:
#    enable: false
#  ignored: "/**"